// meu-app-react/src/idadeAdulto.jsx
import React, { useState, useEffect } from 'react';

const IdadeAdulto = ({ title }) => {
  const [idade, setIdade] = useState(0);
  const [nome, setNome] = useState('');

  const saudacao = () => {
    return `Olá, ${nome}! Você tem ${idade} anos de idade.`;
  };

  const categoriaIdade = () => {
    return idade >= 18 ? 'adulto' : 'menor de idade';
  };

  useEffect(() => {
    console.log('Componente montado');
  }, []);

  const alteraIdade = (event) => {
    setIdade(Number(event.target.value));
  };

  const alteraNome = (event) => {
    setNome(event.target.value);
  };

  return (
    <div>
      <h1>{title}</h1>
      <label htmlFor="nome">Nome:</label>
      <input type="text" id="nome" value={nome} onChange={alteraNome} />
      <br />
      <label htmlFor="idade">Idade:</label>
      <input
        type="number"
        id="idade"
        value={idade}
        onChange={alteraIdade}
      />
      <br />
      <p>{saudacao()}</p>
      <p>Categoria de idade: {categoriaIdade()}</p>
    </div>
  );
};

export default IdadeAdulto;

// meu-app/src/components/IdadeAdulto.vue
<template>
  <div>
    <h1>{{ title }}</h1>
    <label for="nome">Nome:</label>
    <input type="text" id="nome" v-model="nome">
    <br>
    <label for="idade">Idade:</label>
    <input type="number" id="idade" v-model.number="idade">
    <br>
    <p>Categoria de idade: </p>
    <p>{{ categoriaIdade }}</p>
    <slot></slot> 
  </div>
</template>

<script>
export default {
  name: 'IdadeAdulto',
  props: {
    title: String,
    
  },
  data() {
    return {
      idade: 0, 
      nome: '',
    };
  },
  methods: {
    saudacao() {
      return `Olá, ${this.nome}! Você tem ${this.idade} anos de idade.`;
    }
  },
  computed: {
    categoriaIdade() {
      return this.idade >= 18 ? 'adulto' : 'menor de idade';
    }
  },
  mounted() {
    console.log('Componente montado');
  },
  watch: {
    idade(novaIdade, idadeAntiga) {
      console.log(`Nova idade: ${novaIdade}, Idade antiga: ${idadeAntiga}`);
    }
  }
}
</script>

<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
